import Navbar from '@/components/Navbar';
import prisma from '@/db/prisma';
import { Gender, GENDER } from '@/interfaces';
import Banner from '@/components/Banner';
import CategorySideNav from '@/components/CategorySideNav/CategorySideNav';
import NotFound from '@/app/not-found';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

const getGenderCategories = async (gender: GENDER) => {
  const genderFromDB = await prisma.gender.findFirst({
    where: {
      name: gender,
    },
    include: {
      categories: {
        select: {
          id: true,
          name: true,
          genderName: true,
          uriName: true,
        },
      },
    },
  });
  return genderFromDB;
};

export default async function RootLayout({
  children,
  params,
}: {
  children: React.ReactNode;
  params: {
    gender: string;
    category: string;
    productId: string;
  };
}) {
  const genderName = params.gender.toLocaleUpperCase();
  if (genderName === 'MEN' || genderName === 'WOMEN') {
    const categories = await getGenderCategories(genderName);

    const genderObject: Gender | null = await JSON.parse(
      JSON.stringify(categories)
    );

    if (genderObject) {
      return (
        <html lang='en'>
          <body>
            {/* <Navbar /> */}

            <section className='mx-24 pt-36'>
              <div className=' flex '>
                <CategorySideNav genderObject={genderObject} />
                {children}
              </div>
            </section>
          </body>
        </html>
      );
    }
    NotFound();
  }
}
