import Navbar from '@/components/Navbar';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body>
        <Navbar fontColor='text-white' backgroundColor='bg-black'></Navbar>
        {children}
      </body>
    </html>
  );
}
